### ISSUE TITLE
Broken resource strings

### ISSUE THREAD

**Issue by snoozamoorooed** [Athari/CsCss#5]
Hi.
I use Alba.CssCss library in my project for parsing css blocks and found some problems within it related to css error handling.
ErrorReporter class is used for formatting error messages and uses resource strings as format parameter with String.Format call.
Some resource strings have format text incompatible with .net String.Format call.
The problem is with unescaped characters '{' or '}' which have special meaning for string format engine.
Here is an example:
key: PEBadDeclBlockStart
value: Expected '{' to begin declaration block but found '{0}'.
If you call String.Format with such format string FormatException will be thrown.
Correct value would be like this:
Expected '{{' to begin declaration block but found '{0}'.
String.Format replaces "{{" and "}}" with "{" and "}" ...

So i've used pretty simple code to find all similar entries.

            var rm =  new ResourceManager("Alba.CsCss.Globalization.CssResources", typeof(CssStyleSheet).Assembly);
            var resources = rm.GetResourceSet(CultureInfo.CurrentCulture, true, true);
            var badEntries = resources.Cast<DictionaryEntry>().Where(e => e.Key is string && e.Value is string && ((string)e.Value).Contains("{0}") &&
                ((string)e.Value).ToCharArray().Where(c => c == '{').Count() != ((string)e.Value).ToCharArray().Where(c => c == '}').Count()).ToArray();

            var builder = new StringBuilder();
            foreach (var e in badEntries)
            {
                builder.AppendFormat("{0}={1}", e.Key, e.Value).AppendLine();
            }
            Console.WriteLine(builder.ToString());

Here are the entries displayed

PESelectorListExtra=Expected ',' or '{' but found '{0}'.
PESupportsGroupRuleStart=Expected '{' to begin @supports rule but found '{0}'.
PEBadDeclOrRuleEnd2=Expected ';' or '}' to terminate declaration but found '{0}'.
PEBadDeclBlockStart=Expected '{' to begin declaration block but found '{0}'.
PEBadFontBlockEnd=Expected '}' to end @font-face rule but found '{0}'.
PEBadFontBlockStart=Expected '{' to begin @font-face rule but found '{0}'.

**Comment by Athari** [comment]
Please let me know whether it works. I haven't tested the code. :smile:

**Comment by snoozamoorooed** [comment]
It works, thank you

2015-07-18 20:30 GMT+07:00 Alexander Prokhorov notifications@github.com:
