### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by UweKeim** [Athari/CsCss#6]
Do you any plans to support your library running on [.NET Core](https://www.microsoft.com/net/core) in the near future?

**Comment by Athari** [comment]
Have you tried [AngleSharp](https://github.com/AngleSharp/AngleSharp)? When CsCss was created, AngleSharp's CSS functionality was half-cooked, but I bet it's miles ahead now, so I don't see any point in maintaining CsCss really.

Though if you really need CsCss, creating a portable library with support for .NET Core should be relatively easy, I don't think I used any big .NET-specific features.

**Comment by UweKeim** [comment]
Thanks, yes I'm already using AngleSharp in some of my projects. 

TBH I did not yet look into it when it comes to replace your library. Will try!
